name: Azure Stack Hub Validation

on: [pull_request]

jobs:
  validatemodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validation
      uses: "./actions/action-asz-validation"
